repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/joshuachp/pre-commit-hooks
    rev: 0.1.22
    hooks:
      - id: rust-fmt
      - id: rust-clippy
      - id: rust-build
      - id: rust-test
      - id: nix-nixpkgs-fmt
      - id: nix-flake-check
      - id: nix-build
